[package]
name = "fw-pci"
version = "0.1.0"
authors = ["Xiaoyu Lu <xiaoyux.lu@intel.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.13.2"
bitflags = "1.2.1"
x86 = { version = "0.34.0", optional = true}
log = "0.4.13"

tdx-tdcall = { path = "../tdx-tdcall", optional = true }

[features]
default = ["tdcall"]
iocall = ["x86"]
tdcall = ["tdx-tdcall"]
